
server:
  port: 8080
  servlet:
    session:
      timeout: 60
spring:
  application:
    name: spring-security-test
  # dev环境
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
  main:
    allow-bean-definition-overriding: true
#配置dispatchServlet
 # spring.mvc.pathmatch.use-suffix-pattern=true
 # server.servlet.context-path=/
 # server.servlet.path=*.action
mybatis:
  configuration:
    map-underscore-to-camel-case: true
