spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc: mysql://localhost:3306/user?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root


server:
  port: 9000
  servlet:
    context-path: /auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:9001/eureka/